---

enabled: true

debug: false
#WARNING: Your log may get spammed.

block: 19
#Defualt is set to sponge (ID: 19)

economy: true

# ^^ set to true for LuckyBlocks to set money and set min & max values ^^

rewards:

  money: 
    min: -500 #Will only work if economy is enabled and found.
    max: 500

  chest:
    "19" # These are block/items that could appear in chest !
    "1"

  mobs:
    creeper: true
    pig: true      # What mobs could it spawn ?
    cow: true
    skeleton: true
    spider: true

---
