---

enabled: true

debug: false
#WARNING: Your log may get spammed.

block: 19
#Defualt is set to sponge (ID: 19)

economy:
  - enabled: false
  - min: -500
  - max: 500
#set to true for LuckyBlocks to set money and set min & max values

---
